# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BaseFile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for BaseFile
  pod 'AFNetworking', '~> 4.0'
  pod 'MJRefresh', '~> 3.5.0'
  pod 'SVProgressHUD', '~> 2.2.5'
  pod 'IQKeyboardManager', '~> 6.5.6'
  pod 'YYModel', '~> 1.0.4'
  pod 'YYCache', '~> 1.0.4'
  pod 'SDWebImage', '~> 5.0'
  pod 'TZImagePickerController', '~> 3.5.6'
  pod 'CYLTabBarController' # TabBar
  pod 'RTRootNavigationController'
  pod 'Masonry'             # 代码动态布局
  pod 'JXCategoryView'      # 分段控制器
end
